spring:
  profiles:
    group:
      dev : dev
      prod : prod
      demo : demo
    active:
    - dev
    
---
# develop
spring:
  config:
    activate:
      on-profile:
      - dev
      
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://192.168.123.181:5432/mkaieconcamp
    username: mkaieconcamp
    password: mkaieconcamp
    
  jpa:
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      location: C:\\data\\mzcore\\
      max-request-size: 10MB
      max-file-size: 5MB

  devtools:
    livereload:
      enabled: true

---
# product
spring:
  config:
    activate:
      on-profile:
      - prod
      
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://112.220.79.218:18154/mkaieconcamp
    username: mkaieconcamp
    password: mkaieconcamp
  
  jpa:
    open-in-view: false  

  servlet:
    multipart:
      enabled: true
      location: D:\\data\\mzcore\\
      max-request-size: 10MB
      max-file-size: 5MB

---  
# demo
spring:
  config:
    activate:
      on-profile:
      - demo
      
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://112.220.79.218:18154/mkaieconcamp
    username: mkaieconcamp
    password: mkaieconcamp
  
  jpa:
    open-in-view: false  

  servlet:
    multipart:
      enabled: true
      location: C:/data/mzcore/
      max-request-size: 10MB
      max-file-size: 5MB
      
server:
  port: 8081

---  
# common
spring:
  jpa: 
   properties:
     hibernate:
       show-sql: true
       format_sql: true
       use_sql_comments: false
       dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: message/messages  # message/messages 폴더 안의 파일들을 찾음
    encoding: UTF-8
    fallback-to-system-locale: true
    always-use-message-format: true    

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  
  data:
    web:
      pageable: # 페이징 필요없으면 삭제 !
        default-page-size: 10 # 한 페이지에 보여줄 기본 게시글 수
        max-page-size: 10 # 최대 페이지 크기
        one-indexed-parameters: true
        
  mail:
    host: smtp.gmail.com
    port: 587
    username: heeyeon2711@gmail.com # 테스트용
    password: sljm hacl amii wfwg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30
            
server:
  port: 8443  # HTTPS port
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: korean-pro
  http:
    port: 8080  # HTTP port (will redirect to HTTPS)
  error:
    whitelabel:
      enabled: false
    path: /error/404
    
api:
  stt:
    host: 112.220.79.222
    port: 33001
  mirage:
    url: http://112.220.79.222:33004
    db_name: openai_test              # mirage 등록된 db collection 명
  speechpro_kr:
    url: http://112.220.79.222:33005/speechpro
  speechpro_en:
    url: https://112.220.79.218:13725
    id: admin
    pw: mediazen1!